### ISSUE TITLE
Error when fitting NH3

### ISSUE THREAD

**Issue by jpinedaf** [GBTAmmoniaSurvey/GAS#45]
I was running the NH3 fitter for NGC1333 using the following parameters
``GAS.PropertyMaps.cubefit( region='NGC1333', blorder=1, do_plot=True, snr_min=3, multicore=1, vmax=9.5, vmin=4.2)``
but I got the following error message from ``pyspeckit`` that aborted the program 
```
INFO: Fitting  131, 151 (s/n=33) [pyspeckit.cubes.SpectralCube]
INFO: Finished fit   7458 of  10256 at ( 131, 151) s/n= 32.6. Elapsed time is 21919.5 seconds.  %73 [pyspeckit.cubes.SpectralCube]
INFO: Fitting   13, 251 (s/n=32) [pyspeckit.cubes.SpectralCube]
INFO: Finished fit   7459 of  10256 at (  13, 251) s/n= 31.5. Elapsed time is 21920.4 seconds.  %73 [pyspeckit.cubes.SpectralCube]
INFO: Fitting   60, 171 (s/n=35) [pyspeckit.cubes.SpectralCube]
ERROR: Fit number 7459 at 60,171 failed on error ERROR: parameters are not within PARINFO limits [pyspeckit.cubes.SpectralCube]
ERROR: Guesses were: [  5.68222586   2.8         16.28740312   0.38173881   8.14519772   0.5       ] [pyspeckit.cubes.SpectralCube]
ERROR: Fitkwargs were: {'limitedmax': [False, False, False, False, True, True], 'maxpars': [0, 0, 0, 0, 9.5, 1], 'minpars': [5, 2.8, 0, 0, 4.2, 0], 'limitedmin': [True, True, False, True, True, True], 'fittype': 'ammonia', 'fixed': [False, False, False, False, False, True]} [pyspeckit.cubes.SpectralCube]
INFO: Finished fit   7460 of  10256 at (  60, 171) s/n= 34.9. Elapsed time is 21920.5 seconds.  %73 [pyspeckit.cubes.SpectralCube]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-d91344382b2b> in <module>()
----> 1 GAS.PropertyMaps.cubefit( region='NGC1333', blorder=1, do_plot=True, snr_min=3, multicore=1, vmax=9.5, vmin=4.2)

/Users/jpineda/Library/Python/2.7/lib/python/site-packages/GAS-0.2.dev182-py2.7.egg/GAS/PropertyMaps.pyc in cubefit(region, blorder, vmin, vmax, do_plot, snr_min, multicore)
    213                   use_neighbor_as_guess=True,
    214                   position_order = 1/peaksnr,
--> 215                   errmap=errmap11, multicore=multicore)
    216 
    217     fitcubefile = fits.PrimaryHDU(data=np.concatenate([cubes.parcube,cubes.errcube]), header=cubes.header)

/Users/jpineda/Library/Python/2.7/lib/python/site-packages/pyspeckit-0.1.17.dev1839-py2.7.egg/pyspeckit/cubes/SpectralCube.pyc in fiteach(self, errspec, errmap, guesses, verbose, verbose_level, quiet, signal_cut, usemomentcube, blank_value, integral, direct, absorption, use_nearest_as_guess, use_neighbor_as_guess, start_from_point, multicore, position_order, continuum_map, **fitkwargs)
    861         else:
    862             for ii,(x,y) in enumerate(valid_pixels):
--> 863                 fit_a_pixel((ii,x,y))
    864 
    865 

/Users/jpineda/Library/Python/2.7/lib/python/site-packages/pyspeckit-0.1.17.dev1839-py2.7.egg/pyspeckit/cubes/SpectralCube.pyc in fit_a_pixel(iixy)
    755 
    756             if sp.specfit.modelerrs is None:
--> 757                 raise TypeError("The fit never completed; something has gone wrong.")
    758 
    759             if integral:

TypeError: The fit never completed; something has gone wrong.
```

I'll check what is going on, but if you have any clue that would be great! @keflavich @rfriesen @low-sky

**Comment by keflavich** [comment]
This is one of those awful bugs that I find really difficult to track down.  The way to debug it is to extract that single spectrum and try fitting it with precisely the same input parameters.  

The error message says that one of the guesses, or one of the attempted lmfit "moves", is out of limits.  However, from the output, it seems that none are.  This may be a floating point error having to do with imperfect representation of some numbers, or it might be something subtler.  

I might be able to track this down if you post the individual spectrum extracted from that pixel (rather than the cube - I am out of HD space right now...) somewhere.

**Comment by rfriesen** [comment]
I just got the same error on the NGC 1333 map. I can post the individual (1,1) and (2,2) spectra where it crashed - is there a particular format you need?

**Comment by keflavich** [comment]
@rfriesen FITS would be best.  Could you also include the traceback as Jaime did above?  (I need to have the same input parameters)

**Comment by rfriesen** [comment]
@keflavich There was a problem with the rms file used in the fit, so I'm re-running to see if the error recurs - will probably take a day or two. If so, I'll post the traceback and send you the spectra.

**Comment by rfriesen** [comment]
@keflavich Ok, I re-ran the fits and got the same error. The traceback is below. Looking into the spectra, the (1,1) line has a peak S/N of only 3.4, so that might be part of the problem - although I would hope the fitting program would not crash if it can't get a good fit at low S/N? The code is returning a S/N of 41.5, though, so I'm not sure what's happened there. 

The spectra are shared in the NGC 1333 directory Temporary Data Share folder that Alyssa set up during the workshop:
https://drive.google.com/open?id=0B1rOOhYJQqkrSFpLU1hrekljMGc
https://drive.google.com/open?id=0B1rOOhYJQqkrQWdMSVpvQmVRbW8

I *think* I wrote them out correctly but let me know if there are any problems.
--
INFO: Fitting   55, 236 (s/n=42) [pyspeckit.cubes.SpectralCube]                 
ERROR: Fit number 7496 at 55,236 failed on error ERROR: parameters are not within PARINFO limits [pyspeckit.cubes.SpectralCube]                                 
ERROR: Guesses were: [ 13.21974008   2.8         14.82321997   2.02054796   7.46871138   0.5       ] [pyspeckit.cubes.SpectralCube]                             
ERROR: Fitkwargs were: {'limitedmax': [False, False, False, False, True, True], 'maxpars': [0, 0, 0, 0, 15, 1], 'minpars': [5, 2.8, 0, 0, 5, 0], 'limitedmin': [True, True, False, True, True, True], 'fittype': 'ammonia', 'fixed': [False, False, False, False, False, True]} [pyspeckit.cubes.SpectralCube]                  
INFO: Finished fit   7497 of  13023 at (  55, 236) s/n= 41.5. Elapsed time is 65022.4 seconds.  %58 [pyspeckit.cubes.SpectralCube]                              
---------------------------------------------------------------------------     
TypeError                                 Traceback (most recent call last)     
<ipython-input-4-e61d03ee9088> in <module>()
----> 1 GAS.PropertyMaps.cubefit(region='NGC1333',blorder=1,vmin=5,vmax=15,do_plot=False,snr_min=3.0,multicore=1)

/lustre/pipeline/scratch/GAS/python/GAS/GAS/PropertyMaps.pyc in cubefit(region, blorder, vmin, vmax, do_plot, snr_min, multicore)
    357                   use_neighbor_as_guess=True,
    358                   position_order = 1/peaksnr,
--> 359                   errmap=errmap11, multicore=multicore)
    360
    361     fitcubefile = fits.PrimaryHDU(data=np.concatenate([cubes.parcube,cubes.errcube]), header=cubes.header)

/lustre/pipeline/scratch/GAS/python/anaconda/lib/python2.7/site-packages/pyspeckit-0.1.17.dev0-py2.7.egg/pyspeckit/cubes/SpectralCube.pyc in fiteach(self, errspec, errmap, guesses, verbose, verbose_level, quiet, signal_cut, usemomentcube, blank_value, integral, direct, absorption, use_nearest_as_guess, use_neighbor_as_guess, start_from_point, multicore, position_order, continuum_map, **fitkwargs)
    861         else:
    862             for ii,(x,y) in enumerate(valid_pixels):
--> 863                 fit_a_pixel((ii,x,y))
    864
    865

/lustre/pipeline/scratch/GAS/python/anaconda/lib/python2.7/site-packages/pyspeckit-0.1.17.dev0-py2.7.egg/pyspeckit/cubes/SpectralCube.pyc in fit_a_pixel(iixy)
    755
    756             if sp.specfit.modelerrs is None:
--> 757                 raise TypeError("The fit never completed; something has gone wrong.")
    758
    759             if integral:

TypeError: The fit never completed; something has gone wrong.

**Comment by keflavich** [comment]
@rfriesen thanks for the data link; I'll have a look when I get a chance but I'm going to be very busy with travel for the next ~week or few.  I still suspect an annoying corner case involving floating point arithmetic, but I'm not sure.

**Comment by keflavich** [comment]
@rfriesen I'm running the fitter now; I'll see if I can reproduce the error.

**Comment by keflavich** [comment]
I get the same error but at a different pixel:
```
INFO: Finished fit   7359 of  11967 at ( 119,  20) s/n=  3.6. Elapsed time is 35000.6 seconds.  %61 [pyspeckit.cubes.SpectralCube]
INFO: Fitting  142, 124 (s/n=3.9) [pyspeckit.cubes.SpectralCube]
ERROR: Fit number 7359 at 142,124 failed on error ERROR: parameters are not within PARINFO limits [pyspeckit.cubes.SpectralCube]
ERROR: Guesses were: [ 19.29731377   2.8         15.05977155   2.3112405    9.00181435   0.5       ] [pyspeckit.cubes.SpectralCube]
ERROR: Fitkwargs were: {'limitedmax': [False, False, False, False, True, True], 'maxpars': [0, 0, 0, 0, 15, 1], 'minpars': [5, 2.8, 0, 0, 5, 0], 'limitedmin': [True, True, False, True, True, True], 'fittype': 'ammonia', 'fixed': [False, False, False, False, False, True]} [pyspeckit.cubes.SpectralCube]
INFO: Finished fit   7360 of  11967 at ( 142, 124) s/n=  3.9. Elapsed time is 35000.6 seconds.  %62 [pyspeckit.cubes.SpectralCube]
Traceback (most recent call last):
  File "<ipython-input-4-e61d03ee9088>", line 1, in <module>
    GAS.PropertyMaps.cubefit(region='NGC1333',blorder=1,vmin=5,vmax=15,do_plot=False,snr_min=3.0,multicore=1)
  File "/Users/adam/repos/GAS/GAS/PropertyMaps.py", line 359, in cubefit
    errmap=errmap11, multicore=multicore)
  File "/Users/adam/repos/pyspeckit/pyspeckit/cubes/SpectralCube.py", line 875, in fiteach
    fit_a_pixel((ii,x,y))
  File "/Users/adam/repos/pyspeckit/pyspeckit/cubes/SpectralCube.py", line 769, in fit_a_pixel
    raise TypeError("The fit never completed; something has gone wrong.")
TypeError: The fit never completed; something has gone wrong.
```

**Comment by keflavich** [comment]
The problem is that the second parameter is exactly equal to one of the limits.

**Comment by keflavich** [comment]
Actually, it's exactly 1 [ULP](https://en.wikipedia.org/wiki/Unit_in_the_last_place) below 2.8, which is what has caused the failure.  The value is 2.7999999999999994, but the closest representable # to 2.8 is 2.7999999999999998.  I'll have to implement a few extra checks.

**Comment by keflavich** [comment]
I've merged the changes into master now; give it another shot.  I'll try today if I can but I'm worried about my compy overheating

**Comment by rfriesen** [comment]
I've just run the Perseus maps and didn't have any errors. Looks great, thanks! Trying Orion A now.

**Comment by rfriesen** [comment]
@keflavich I'm getting the same error on the Orion A map, still, even though the NGC 1333 map finished with no problems. The second parameter is again being reported as 2.8. I've updated the GAS installation of pyspeckit to 0.1.17.dev, so I think we have the version with your fix included.

**Comment by keflavich** [comment]
We have entered spooky territory.  OK, I'll get on this, but not before the weekend.

**Comment by low-sky** [comment]
I'll just add that I've encountered similar issues in earlier versions and figured it was just my problem.

**Comment by low-sky** [comment]
Stupid wrong button.

**Comment by keflavich** [comment]
could one of you set the logger level to DEBUG (`log.setLevel(10)`) and run the failure again?  It... may be too much, actually (you might have to ctrl-c to cut off the printing if its excessive), so could also try `log.setLevel(20)`, but it would help to have more info.

**Comment by jpinedaf** [comment]
@rfriesen Could you please post the exact command you run?

**Comment by jpinedaf** [comment]
I got it to work with the following command on the old data:
```
In [9]: GAS.PropertyMaps.cubefit(region='OrionA', vmin=5.6, vmax=13.7, do_plot=False, snr_min=3.0, 
            multicore=40)
```
I still need to run it using the latest reduction of the data

**Comment by keflavich** [comment]
With the data on google drive, I got to 57% without encountering an error; that was my time limit on my laptop for now.  However, I have another smaller cube that reproduces a *similar* error in much less time, so I'll work on that.

**Comment by rfriesen** [comment]
On the updated Orion A data (I can post to drive later today), the error comes at 58%. I'll try again with Jaime's limited velocity range. @jpinedaf , are you running on GB machines or on your own? The only difference between my call and yours is an extended velocity range in vmin/vmax.
@keflavich Sorry, I'm still working on my python-fu - where would I set the logger level?

**Comment by keflavich** [comment]
58%?!  You're kidding.  I could've waited 2 minutes... sigh.

@rfriesen to set the log level, use astropy's logging configurator:
```
from astropy import log
log.setLevel("DEBUG")
```
(I just learned this syntax from Tom R. last week; there's always something new to learn!)

@jpinedaf - if you could start up the expected failure tonight or tomorrow morning, I can come by tomorrow and try to figure out what's up.  Please run it in serial mode; debugging is much more difficult (or impossible) in parallel mode.

**Comment by jpinedaf** [comment]
@rfriesen I'm doing it at MPE... that is why I've only done to the old data

@keflavich It is running now... in serial mode, lets see if it finishes on time :)

**Comment by keflavich** [comment]
@jpinedaf is the data on google drive Old or New?  I was using that.

**Comment by jpinedaf** [comment]
@keflavich It is still Old... that is what I've been using

**Comment by rfriesen** [comment]
@keflavich @jpinedaf I just ran the *new* Orion A dataset on a GB machine with Jaime's velocity range, using the logger 'DEBUG' level. I get the error at 28% (my original call used a S/N = 5 threshold, not S/N = 3, hence the lower %) and it looks like the error reporting doesn't give that much more information (see below).  Just to check, though, pyspeckit says it finished fit 6850 at (50,46), but later says fit 6850 at 68,36 failed. Is that just a counting issue? Because there's a whole lot of debug messages for the (50,46) fit (I don't keep enough lines in my terminal to print them all!) but from the messages I think that's not the one that's the problem. I included a few of the previous lines in case they're helpful, let me know if you'd like to see more. 

DEBUG: at 'test for successful iteration' ratio=3.90300570885 fnorm=70.4483851925 [pyspeckit.mpfit.mpfit]                                                       
DEBUG: BREAK with status: 5 [pyspeckit.mpfit.mpfit]                             
DEBUG: BREAK with status: 5 [pyspeckit.mpfit.mpfit]                             
DEBUG: in the termination phase [pyspeckit.mpfit.mpfit]                         
DEBUG: Entering call with x=[ 14.83725786  68.46781433  13.41640426   0.39934639   9.18665156   0.5       ]... [pyspeckit.mpfit.mpfit]                          
DEBUG: After iterations, status=5 fnorm=70.4483851925 [pyspeckit.mpfit.mpfit]   
DEBUG: After iterations, fnorm=4962.97497624 [pyspeckit.mpfit.mpfit]     
INFO: Finished fit   6850 of  24359 at (  50,  46) s/n= 37.3. Elapsed time is 65192.3 seconds.  %28 [pyspeckit.cubes.SpectralCube]       
INFO: Fitting   60, 336 (s/n=37) [pyspeckit.cubes.SpectralCube]                 
DEBUG: Exclude: None [pyspeckit.spectrum.interactive]                           
DEBUG: Entering parinfo... [pyspeckit.mpfit.mpfit]                              
DEBUG: Entering parinfo... [pyspeckit.mpfit.mpfit]                              
DEBUG: Entering parinfo... [pyspeckit.mpfit.mpfit]                              
DEBUG: Entering parinfo... [pyspeckit.mpfit.mpfit]                              
DEBUG: Entering parinfo... [pyspeckit.mpfit.mpfit]                              
DEBUG: Entering parinfo... [pyspeckit.mpfit.mpfit]                              
DEBUG: Entering parinfo... [pyspeckit.mpfit.mpfit]                              
DEBUG: Entering parinfo... [pyspeckit.mpfit.mpfit]                              
DEBUG: Entering parinfo... [pyspeckit.mpfit.mpfit]                              
DEBUG: Entering parinfo... [pyspeckit.mpfit.mpfit]                              
DEBUG: Entering parinfo... [pyspeckit.mpfit.mpfit]                              
ERROR: Fit number 6850 at 60,336 failed on error ERROR: parameters are not within PARINFO limits [pyspeckit.cubes.SpectralCube]                                 
ERROR: Guesses were: [  2.39116022e+02   2.80000000e+00   1.45991903e+01   5.25665869e-02                                                                       
   6.45507416e+00   5.00000000e-01] [pyspeckit.cubes.SpectralCube]              
ERROR: Fitkwargs were: {'limitedmax': [False, False, False, False, True, True], 'maxpars': [0, 0, 0, 0, 13.7, 1], 'minpars': [5, 2.8, 0, 0, 5.6, 0], 'limitedmin': [True, True, False, True, True, True], 'fittype': 'ammonia', 'fixed': [False, False, False, False, False, True]} [pyspeckit.cubes.SpectralCube]              
INFO: Finished fit   6851 of  24359 at (  60, 336) s/n= 37.3. Elapsed time is 65192.7 seconds.  %28 [pyspeckit.cubes.SpectralCube]                              
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-18-949407443cfe> in <module>()
----> 1 GAS.PropertyMaps.cubefit(region='OrionA',blorder=1,vmin=5.6,vmax=13.7,do_plot=False,snr_min=3.0,multicore=1)

/lustre/pipeline/scratch/GAS/python/GAS/GAS/PropertyMaps.pyc in cubefit(region, blorder, vmin, vmax, do_plot, snr_min, multicore)
    357                   use_neighbor_as_guess=True,
    358                   position_order = 1/peaksnr,
--> 359                   errmap=errmap11, multicore=multicore)
    360
    361     fitcubefile = fits.PrimaryHDU(data=np.concatenate([cubes.parcube,cubes.errcube]), header=cubes.header)

/lustre/pipeline/scratch/GAS/python/anaconda/lib/python2.7/site-packages/pyspeckit-0.1.17.dev0-py2.7.egg/pyspeckit/cubes/SpectralCube.pyc in fiteach(self, errspec, errmap, guesses, verbose, verbose_level, quiet, signal_cut, usemomentcube, blank_value, integral, direct, absorption, use_nearest_as_guess, use_neighbor_as_guess, start_from_point, multicore, position_order, continuum_map, **fitkwargs)
    878         else:
    879             for ii,(x,y) in enumerate(valid_pixels):
--> 880                 fit_a_pixel((ii,x,y))
    881
    882

/lustre/pipeline/scratch/GAS/python/anaconda/lib/python2.7/site-packages/pyspeckit-0.1.17.dev0-py2.7.egg/pyspeckit/cubes/SpectralCube.pyc in fit_a_pixel(iixy)
    772
    773             if sp.specfit.modelerrs is None:
--> 774                 raise TypeError("The fit never completed; something has gone wrong.")
    775
    776             if integral:

TypeError: The fit never completed; something has gone wrong.

**Comment by keflavich** [comment]
@rfriesen - the numbers are all wrong when run in parallel; there are a bunch of "race conditions" and it is never clear what order things happen with respect to the numbers being printed on screen.  In any case, I found a loophole related to this error and am working to close it

**Comment by jpinedaf** [comment]
I'm running the fitter for the new OrionA data (no debug) just to see if there is still the same problem... hopefully I'll give an answer soon

**Comment by jpinedaf** [comment]
I can confirm that it also works on the "new OrionA" data. I did run it using the multicore option, so I'll leave it later running on serial mode to compare results.
